import React from 'react';
import Head from "next/head";
import Hero from '../../components/hero';
import Gallery from '../../components/gallery';
import Map from '../../components/map';
export const getStaticPaths = async () => {
    const res = await fetch("http://localhost/listmeon/api/allBusiness.php")
    const allBusiness = await res.json();
    const allSlug = allBusiness.map((business) => {
        return {
            params: { slug: business.slug }
        }
    })
    return {
        paths: allSlug,
        fallback: false
    }
}
export const getStaticProps = async (context) => {
    const slug = context.params.slug;
    const res = await fetch(`http://localhost/listmeon/api/singleBusiness.php?slug=${slug}`);
    const data = await res.json();
    return {
        props: { singleBusiness: data }
    }
}
const Slug = ({ singleBusiness }) => {
    return (
        <>
            <Head>
                <title>Listmeon | {singleBusiness[0].firm_name}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero singleBusiness={singleBusiness} />
            {/* <Gallery /> */}
            <Map />
        </>
    )
}

export default Slug
