import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Hero from "../components/hero";
import Gallery from "../components/gallery";
import Map from "../components/map";
export default function Home() {
  return (
    <>
      <Head>
        <title>Listmeon | index page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container text-center">
        <h1>welcome to index</h1>
        <Link href="/home">
          <a className="btn btn-primary">home</a>
        </Link>
      </div>

      {/*<Hero />
      <Gallery />
      <Map /> */}
    </>
  );
}
