import Head from "next/head";
import Image from "next/image";
import Hero from "../components/hero";
import Gallery from "../components/gallery";
import Map from "../components/map";
import styles from "../styles/Home.module.css";
import Footer from "../components/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Gallery />
      <Map />
      <Footer />
    </>
  );
}
